replicaCount: 1

image:
  repository: hub.bitkinetic.com/public/lark
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
# serviceaccount: micro-registry
# 服务名称，基于 kubernetes 的服务注册与发现依赖此项
# hostName: 'dn.micro.srv.message'
envs: 
  GO_MICRO_ENV:  dev
  MICRO_SERVER_ADDRESS: :9052
  MICRO_REGISTRY_ADDRESS: consul:8500
  # MICRO_REGISTER_TTL: '6'
  # MICRO_REGISTER_INTERVAL: '3'
  MICRO_REGISTRY: consul
ports:
  grpc: 0
  http: 80
httpHealthyPath: '/health' #http 健康检查路径，启用了 http 端口并且设置了此路径则启用
# 配置信息
configs: 
service:
  type: ClusterIP
resources: 
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 10m
    memory: 50Mi
# nodeSelector:
#   svc: koolio
# tolerations:
#   - key: purpose
#     operator: Equal
#     value: koolio
#     effect: NoExecute

affinity: {}